### ISSUE TITLE
Invalid function error when executing epkg-list-packages.

### ISSUE THREAD

**Issue by BrendanLeber** [emacscollective/epkg#11]
The update that switched to using `if-let*` (a9a8b369d77db7887b5244de4db847c3b7316590) seems to have broken `epkg-list-packages`.  Now when I execute this function I get the following error message:

```elisp
Debugger entered--Lisp error: (invalid-function (pp (nth 5 col)))
  (pp (nth 5 col))()
```
The call to `pp` happens inside of `epkg--list-packages`.  If I edit my local copy to replace `if-let*` with `if-let` it works as expected.  Also, using the same version of emacs works if I clone a fresh copy of emacs.g and use it.  

Emacs Version: GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars) of 2017-09-12

**Comment by tarsius** [comment]
I have reverted that commit. I did not realize (or rather I had forgotten) that `if-let*` doesn't exist in 25.3.

Thanks for the report.

**Comment by BrendanLeber** [comment]
Thanks!
