### ISSUE TITLE
Error when using epkg-describe-package

### ISSUE THREAD

**Issue by Luladjiev** [emacscollective/epkg#13]
Using Emacs 25.3.1 when trying epkg-describe-package I get this error:

apply: Args out of range: "vector", 17, nil

Using emacscollective/emacs.g to manage all packages, this error happens after one of the latest pulls I made to epkg.

**Comment by tarsius** [comment]
Not sure this is the case here, but this might just be another symptom of the issue I mention at #12.

**Comment by Luladjiev** [comment]
Still not working with a fresh clone of my configuration. However I've checkout the same version as emacscollective/emacs.g of epkg which is [6114b78](https://github.com/emacscollective/epkg/tree/6114b78b84cd8a96a117b7652d1e5138eee4b896) and it does work. Previously I was using the latest commit of epkg [6172b4cc](https://github.com/emacscollective/epkg/tree/6172b4cc5247cbfbcfb87ad856a70d617326c760). Later I may bisect the changes to see which commit breaks the epkg. For now I'll use the same as emacscollective/emacs.g

**Comment by tarsius** [comment]
Please also post a full backtrace.

**Comment by Luladjiev** [comment]
Sorry about that. Here is the stacktrace:


``Debugger entered--Lisp error: (args-out-of-range "vector" 17 nil)
  #[257 "\300\301\302!\303\304O!!\207" [closql--abbrev-class intern symbol-name 17 nil] 6 "\n\n(fn CLASS-TAG)"](vector)
  apply(#[257 "\300\301\302!\303\304O!!\207" [closql--abbrev-class intern symbol-name 17 nil] 6 "\n\n(fn CLASS-TAG)"] vector nil)
  closql--abbrev-class(vector)
  epkg-describe-package-1([eieio-class-tag--epkg-github-package [eieio-class-tag--epkg-database #<process emacsql-sqlite> nil "/home/luladjiev/.emacs.d/var/epkgs/epkg.sqlite"] "a" "d50b953cb0a7402107cdd6275cff9d31d09835a3" "git@github.com:plexus/a.el.git" "git@github.com:emacsmirror/a.git" "a" "plexus" "a.el" nil nil nil "https://github.com/plexus/a.el" "https://github.com/plexus/a.el" "https://github.com/emacsmirror/a" nil "GPL-3+" "2017" "20171112" "Associative data structure functions" "Library for dealing with associative data structures: alists, hash-maps, and\nvectors (for vectors, the indices are treated as keys).\n\nThis library is largely inspired by Clojure, it has many of the functions\nfound in clojure.core, prefixed with `a-'. All functions treat their\narguments as immutable, so e.g. `a-assoc' will clone the hash-table or alist\nit is given. Keep this in mind when writing performance sensitive code.\n" nil ((a nil nil)) ((cl-lib t nil nil) (seq t nil nil) (subr-x t nil nil)) (lisp) (("Arne Brasseur" "arne@arnebrasseur.net")) (("Arne Brasseur" "arne@arnebrasseur.net")) ([eieio-class-tag--melpa-github-recipe [eieio-class-tag--epkg-database #<process emacsql-sqlite> nil "/home/petar.luladjiev/.emacs.d/var/epkgs/epkg.sqlite"] "a" "git@github.com:plexus/a.el.git" "plexus/a.el" "https://github.com/plexus/a.el" nil nil nil nil nil nil "a"]) nil nil nil])
  epkg-describe-package("a")
  epkg-list-describe-package(#<marker (moves after insertion) at 422 in *Epkgs*>)
  button-activate(#<marker (moves after insertion) at 422 in *Epkgs*> nil)
  push-button(422)
  funcall-interactively(push-button 422)
  call-interactively(push-button nil nil)
  command-execute(push-button)``

**Comment by tarsius** [comment]
Did you update the `epkgs` repository recently?

**Comment by Luladjiev** [comment]
With **epkg-update** yes

**Comment by jabranham** [comment]
I also experience this error with an updated epkgs repository. Backtrace:

```
Debugger entered--Lisp error: (args-out-of-range "vector" 17 nil)
  #[257 "\300\301\302!\303\304O!!\207" [closql--abbrev-class intern symbol-name 17 nil] 6 "\n\n(fn CLASS-TAG)"](vector)
  apply(#[257 "\300\301\302!\303\304O!!\207" [closql--abbrev-class intern symbol-name 17 nil] 6 "\n\n(fn CLASS-TAG)"] vector nil)
  closql--abbrev-class(vector)
  epkg-describe-package-1([eieio-class-tag--epkg-github-package [eieio-class-tag--epkg-database #<process emacsql-sqlite<1>> nil "/home/alex/.emacs.d/var/epkgs/epkg.sqlite"] "helm" "fd71d598b8160f07d7151d898e17001d1d39bb0c" "git@github.com:emacs-helm/helm.git" "git@github.com:emacsmirror/helm.git" "helm" "emacs-helm" "helm" nil nil nil "https://github.com/emacs-helm/helm" "http://github.com/emacs-helm/helm" "https://github.com/emacsmirror/helm" "https://emacswiki.org/Helm" "GPL-3+" "2007" "20171207" "Emacs incremental and narrowing framework" nil nil ((helm nil nil) (helm-adaptive nil nil) (helm-apt nil nil) (helm-bookmark nil nil) (helm-buffers nil nil) (helm-color nil nil) (helm-command nil nil) (helm-config nil nil) (helm-dabbrev nil nil) (helm-easymenu nil nil) (helm-elisp nil nil) (helm-elisp-package nil nil) (helm-eshell nil nil) (helm-eval nil nil) (helm-external nil nil) (helm-files nil nil) (helm-find nil nil) (helm-font nil nil) (helm-for-files nil nil) (helm-grep nil nil) (helm-help nil nil) (helm-id-utils nil nil) (helm-imenu nil nil) (helm-info nil nil) (helm-lib nil nil) (helm-locate nil nil) (helm-man nil nil) (helm-misc nil nil) (helm-mode nil nil) (helm-multi-match nil nil) (helm-net nil nil) (helm-org nil nil) (helm-regexp nil nil) (helm-ring nil nil) (helm-semantic nil nil) (helm-source nil nil) (helm-sys nil nil) (helm-tags nil nil) (helm-types nil nil) (helm-utils nil nil) (helm-x-files nil nil)) ((advice t nil nil) (async t nil nil) (async-bytecomp nil nil nil) (bookmark t nil nil) (browse-url t nil nil) (cl-lib t nil nil) (dired t nil nil) (dired-async t nil nil) (dired-aux t nil nil) (dired-x t nil nil) (easymenu t nil nil) (edebug t nil nil) (eieio t nil nil) (eldoc t nil nil) (elisp-mode nil nil nil) (em-alias t nil nil) (etags t nil nil) (ffap t nil nil) (filecache t nil nil) (find-cmd t nil nil) (find-func t nil nil) (helm-ls-git nil nil nil) (helm-ls-hg nil nil nil) (helm-ls-svn nil nil nil) (ido t nil nil) (image-dired t nil nil) (imenu t nil nil) (info t nil nil) (jabber t nil nil) (json t nil nil) (lpr t nil nil) (mml t nil nil) (org t nil nil) (org-indent t nil nil) (org-macs t nil nil) (package t nil nil) (popup t nil nil) (recentf t nil nil) (semantic t nil nil) (thingatpt t nil nil) (time t nil nil) (tramp t nil nil) (url t nil nil) (vc t nil nil) (wdired t nil nil) (wgrep-helm nil nil nil) (winner t nil nil) (woman t nil nil) (xml t nil nil)) nil (("Thierry Volpiatto" "thierry.volpiatto@gmail.com")) (("Thierry Volpiatto" "thierry.volpiatto@gmail.com")) ([eieio-class-tag--melpa-github-recipe [eieio-class-tag--epkg-database #<process emacsql-sqlite<1>> nil "/home/alex/.emacs.d/var/epkgs/epkg.sqlite"] "helm" "git@github.com:emacs-helm/helm.git" "emacs-helm/helm" "https://github.com/emacs-helm/helm" ("*.el" "emacs-helm.sh" (:exclude "helm.el" "helm-lib.el" "helm-source.el" "helm-multi-match.el" "helm-core-pkg.el")) nil nil nil nil nil "helm"] [eieio-class-tag--melpa-github-recipe [eieio-class-tag--epkg-database #<process emacsql-sqlite<1>> nil "/home/alex/.emacs.d/var/epkgs/epkg.sqlite"] "helm-core" "git@github.com:emacs-helm/helm.git" "emacs-helm/helm" "https://github.com/emacs-helm/helm" ("helm-core-pkg.el" "helm.el" "helm-lib.el" "helm-source.el" "helm-multi-match.el") nil nil nil nil nil "helm"]) nil nil nil])
  epkg-describe-package("helm")
  funcall-interactively(epkg-describe-package "helm")
  call-interactively(epkg-describe-package nil nil)
  command-execute(epkg-describe-package)
```

**Comment by tarsius** [comment]
I have pushed a fix.
