### ISSUE TITLE
3.0.0 fails with emacsql 2.0.3

### ISSUE THREAD

**Issue by bremner** [emacscollective/epkg#15]
How about a new tagged release for e.g. melpa-stable users?  3.0.0 is still looking for `emacsql-system.el` which doesn't exist anymore in 2.0.3.

**Comment by tarsius** [comment]
> 3.0.0 is still looking for `emacsql-system.el`

Where does it do that? Epkg does not `require` the feature `emacsql-system` anywhere and it also does not declare the package `emacs-system` to be a dependency. (I don't think that library even was distributed as a separate package at some point.) `epkg` depends on `closql`, which depends on `emacsql-sqlite`, which depends on `emacsql`, which doesn't depend on any packages.

You probably just have to update `emacsql-sqlite` and `emacsql`. If you have already done that, then my guess is that you have old version laying around (possibly just the `*.elc` files), so removing all that and reinstalling might do the trick.

Maybe I am guessing wrong, in that case you will have to tell me how you came to the conclusion that "3.0.0 is still looking for `emacsql-system.el`". Did get an error message? From whom -- `package.el`, `epkg`, `emacsql` or something else? A backtrace might help.

**Comment by tarsius** [comment]
But regardless, it probably is time for another release. I'll look into that, but would like to resolve this issue first. If there actually is something wrong with the packaging, then a new release would likely have the same issue because I am not aware of a defect that I could fix to prevent that.

**Comment by bremner** [comment]
Jonas Bernoulli <notifications@github.com> writes:

>> 3.0.0 is still looking for `emacsql-system.el`
>
> Where does it do that? Epkg does not `require` the feature
> `emacsql-system` anywhere and it also does not declare the package
> `emacs-system` to be a dependency. (I don't think that library even
> was distributed as a separate package at some point.) `epkg` depends
> on `closql`, which depends on `emacsql-sqlite`, which depends on
> `emacsql`, which doesn't depend on any packages.
>
> You probably just have to update `emacsql-sqlite` and `emacsql`. If
> you have already done that, then my guess is that you have old version
> laying around (possibly just the `*.elc` files), so removing all that
> and reinstalling might do the trick.
>
> Maybe I am guessing wrong, in that case you will have to tell me how
> you came to the conclusion that "3.0.0 is still looking for
> `emacsql-system.el`". Did get an error message? From whom --
> `package.el`, `epkg`, `emacsql` or something else? A backtrace might
> help.

Sorry about the lack of information, I thought the release timeline told
the story but I was wrong.

It looks like a bug in emacsql-sqlite3 2.0.3 on melpa-stable.

line 24 reads

     (require 'emacsql-system)

Strangly, if I look at the tag 2.0.3, then it has the file
emacsql-system.el. It looks like maybe melpa-stable is confused by 2.0.3
not being on master, and decided to package master as 2.0.3?

I guess this is not an epkg issue in any case. I'd appreciate advice
whether it's useful to file this with emacsql or melpa-stable.

d

**Comment by tarsius** [comment]
I think `emacsql` was broken on Melpa-Stable ever since it was split into multiple packages. The recipe should probably look like this:

```lisp
(emacsql :repo "skeeto/emacsql"
         :fetcher github
         :files ("emacsql.el"
		 "emacsql-compiler.el"
		 ;; While this file doesn't exist on "master" anymore,
		 ;; it is still part of the latest release (2.0.3).
		 "emacsql-system.el"
		 "README.md"))
```

But I can't remember if updating the recipe causes the latest release to be rebuild.

**Comment by tarsius** [comment]
`emacsql-2.0.3` has been rebuild and now contains `emacsql-system.el`.
