### ISSUE TITLE
3.0.0 is not usable with the current database.

### ISSUE THREAD

**Issue by bremner** [emacscollective/epkg#18]
I copied emacsql-system.el to fix/work-around the packaging bug in melpa-stable, but since epkg-db-version was bumped to 4, it seems epkg 3.0.0 is not usable with the current database.

**Comment by tarsius** [comment]
I'll also have to create a new `closql` release because of #16.

**Comment by tarsius** [comment]
I just create a new release.

**Comment by bremner** [comment]
Jonas Bernoulli <notifications@github.com> writes:

> I'll also have to create a new `closql` release because of #16.

Thanks for all your efforts. I've just successfully installed epkg 3.1.0
from melpa-stable.

d
