### ISSUE TITLE
FUNDING.yml is malformed

### ISSUE THREAD

**Issue by raxod502** [emacscollective/epkg#24]
When clicking the "Sponsor" button one gets the following error message from GitHub:

<img width="458" alt="image" src="https://user-images.githubusercontent.com/6559064/60301051-47bcd080-98e5-11e9-872e-fd439b161c7f.png">

**Comment by tarsius** [comment]
[I am aware](https://github.com/magit/magit/issues/3903) but since "fixing" it would require commits to a few dozen repositories I am not doing it.
