### ISSUE TITLE
Support shallow clone epkgs in epkg-db

### ISSUE THREAD

**Issue by cireu** [emacscollective/epkg#27]
Store the commit history  of epkgs take tons of disk space since epkgs repo contains a single binary sqlite database. And it's useless to access history for most daily usage. Would you like to add an option to specify the clone depth of epkgs?

**Comment by tarsius** [comment]
> Would you like to add an option to specify the clone depth of epkgs?

No. But users can of course clone like that manually.

Instead we should stop checking in the database itself and instead write to a log which would then be used the regenerate the database. Sqlite supports that but I never got around to look into this. Maybe you can look into that?

**Comment by cireu** [comment]
I think you mean the `.dump` and `.read` in sqlite3 cli. `.dump` will convert a table into some SQL statement to create this table. And `.read` can execute these statements.

![图片](https://user-images.githubusercontent.com/18224684/68542628-93ca6680-03e9-11ea-9558-e4ea279d3d50.png)

**Comment by tarsius** [comment]
Since I won't add any support for shallow cloning, so I am closing this.  My private todo list already contains an entry about using a dump file.  I have actually worked on that yesterday and it basically works but making sure migration is as smooth as possible will be a lot of work and I delay that until I feel I have enough time to do it.

**Comment by cireu** [comment]
That sounds good, you may use CI to dump the database automatically and put the artifact and original database in different branch of the same repo.

**Comment by cireu** [comment]
https://github.com/cireu/epkgs-sql

I create a repo and use Github Action to sync from emacsmirror/epkgs and generate SQL file every 30 minutes. If you have interest in it, I can help port this Github Action to this repo.

**Comment by tarsius** [comment]
> I create a repo [to] generate SQL file every 30 minutes.

Thanks. Maybe some other users will find that useful.

> If you have interest in it, I can help port this Github Action to this repo.

No thanks.

The dumping itself boils down `sqlite3 "${SOURCE}" .dump >> "${DIST}"`, which I have known about for a long time and would already have done if there weren't a lot of other things I feel would have to be done at the same time.

So, no thanks.

**Comment by tarsius** [comment]
It's done: https://github.com/emacscollective/borg/issues/91.

**Comment by cireu** [comment]
Awesome!
