### ISSUE TITLE
How can I update epkg database?

### ISSUE THREAD

**Issue by conao3** [emacscollective/epkg#30]
Hello,

The dependency of `ddskk` is still old.
`ddskk` is not (currently) dependent on `apel` or `w3m`. [MELPA - ddskk](https://melpa.org/#/ddskk)
How can I update this information?
```
[-] Dependencies:
 |-[+] apel  github  path-util, static
 |-[+] cl-lib  builtin  cl-lib
 |-[+] compile  builtin  compile
 |-[+] eieio  builtin  eieio
 |-[+] emacs  builtin  advice, comint, cus-edit, custom, easymenu, html2text, ja-dic-utl, japan-util, tooltip, wid-edit
 |-[+] ispell  builtin  ispell
 |-[+] json  builtin  json
 |-[+] lookup  github  lookup
 |-[+] unknown  unknown  nicola-ddskk-autoloads
 |-[+] python  elpa-core  python
 |-[+] ring  builtin  ring
 |-[+] tar-mode  builtin  tar-mode
 |-[+] url  builtin  url, url-http, url-util
 |-[+] viper  builtin  viper
 `-[+] w3m  github  w3m, w3m-search

[-] Reverse dependencies:
 |-[+] ac-skk  github  context-skk, skk, skk-comp
 |-[+] ddskk-posframe  github  skk
 `-[+] ido-skk  github  skk
```

**Comment by tarsius** [comment]
`ddskk` in the Emacsmirror is up-to-date.

The Emacsmirror mirrors complete Git repositories, while the Melpa only extracts and distributes a subset of files. This obviously can result in the Emacsmirror knowing about more dependencies as well. In this case `./experimental/skk-w3m.el` is what depends on `w3m`.

**Comment by conao3** [comment]
I understand, thanks.

**Comment by conao3** [comment]
If we put `.nosearch` file in `experimental` folder, can I get rid of my dependency on `w3m`?
This file is obviously experimental and not maintained.

**Comment by tarsius** [comment]
Yes, that works as you expect.

**Comment by conao3** [comment]
Thanks!
