### ISSUE TITLE
Is it possible to add a package that does not exist in emacsmirror?

### ISSUE THREAD

**Issue by lld2001** [emacscollective/epkg#31]
I use `epkg` with [borg](https://github.com/emacscollective/borg). Some repos not host in emacsmirror.

**Comment by tarsius** [comment]
Which repos?

**Comment by lld2001** [comment]
Sorry, I mean package. For example, https://github.com/manateelazycat/color-rg.git. I do it by `git submodule add` to lib/color-rg. `borg` can not load it.

**Comment by tarsius** [comment]
[I only read the body but not the title of this issue before answering. When I noticed my mistake I deleted that--a few seconds before your reply to my reply came in. Sorry about that.]

Yes, at the `Assimilate package: ` prompt just enter the package name. If that is unknown, then you will get a second prompt, asking for an URL.

**Comment by lld2001** [comment]
That works. Thank you.
