### ISSUE TITLE
Outdated docstring?

### ISSUE THREAD

**Issue by dalugm** [emacscollective/epkg#39]
https://github.com/emacscollective/epkg/blob/bede20656dd5b7cd83da9238b6ef5c2e05313fb9/lisp/epkg.el#L78-L88

I noticed that the `emacsql-sqlite-builtin` repo has been deleted from the github. 

Did it have been moved to another place (such as sr.ht), or just have completed its duty, and we should use the built-in functions of Emacs? Which value should be used for now? thx

**Comment by tarsius** [comment]
It's in the process of being merged into EmacSQL itself. See https://github.com/magit/emacsql/pull/86. We are getting really close now. The current version can be found in the `next` branch of `magit/emacsql` (the new official repository of EmacSQL). Melpa currently gets `emacsql-sqlite-builtin` from that branch.

**Comment by dalugm** [comment]
I see, thanks for the working!
