### ISSUE TITLE
epkg-update fails with Error: cannot open epkg.sql

### ISSUE THREAD

**Issue by Eason0210** [emacscollective/epkg#42]
Hi @tarsius 

with latest commit, `M-x epkg-update `will failed with the error as bellow:

```
epkg-db: Failed to read /Users/eason/.emacs.d/var/epkgs/epkg.sql: Error: cannot open "/Users/eason/.emacs.d/var/epkgs/epkg.sql"
```
steps to reproduce:
1. remove the **epkgs** folder and create a new empty one
2. start Emacs and run `M-x epkg-update`
3. You will get the error mentioned above.

I also can reproduce it with the [emacs.g](https://github.com/emacscollective/emacs.g) Borg seed.
```
make bootstrap-borg 
make bootstrap 
```
And then start Emacs, run `M-x epkg-update,` will get the error.

My Emacs version:
GNU Emacs 30.0.50 (build 1, x86_64-apple-darwin22.4.0, NS appkit-2299.50 Version 13.3.1 (a) (Build 22E772610a), git sha1 a7dcc0d55c6) of 2023-05-14

**Comment by tarsius** [comment]
I cannot reproduce that, and think this is something you will have to figure out on your own.

Try cloning `epkgs` manually. If that by itself does not help, then also make sure `epkg`, `borg`, `emacsql` and `closql` are up-to-date. Look into which sqlite backend is being used. Try with Emacs 29.0.91.

**Comment by Eason0210** [comment]
> Try cloning `epkgs` manually. If that by itself does not help, then also make sure `epkg`, `borg`, `emacsql` and `closql` are up-to-date. Look into which sqlite backend is being used. Try with Emacs 29.0.91.

Thanks for you advice. I try cloning `epkgs` manually by `git clone https://github.com/emacsmirror/epkgs.git` and then `epkg-update` works expected.
