### ISSUE TITLE
epkg-list-matching-packages should match against package names also

### ISSUE THREAD

**Issue by caadar** [emacscollective/epkg#5]
Some packages e.g. `epkg`, `trashcan`, `zygospore` could not be found by `epkg-list-matching-packages`.

These packages are shown by `epkg-list-packages` though.

**Comment by tarsius** [comment]
These two sentences seem to contradict each other.

**Comment by tarsius** [comment]
This command searches the package summary only. If I search for `Emacsmirror` for example, then `epkg` is listed.

**Comment by caadar** [comment]
> These two sentences seem to contradict each other.

Corrected last one.

**Comment by caadar** [comment]
> This command searches the package summary only.

Indeed, overlooked this.

But why not to include in search result matching packages names also? It will be more expected.
